---
format: 
  pdf:
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf PHIL HENRICKSON}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}phil.henrickson@gmail.com ∙ Madison, WI ∙ \href{https://phenrickson.github.io}{Personal Site} ∙ \href{https://github.com/phenrickson}{GitHub} ∙ \href{https://www.linkedin.com/in/phenrickson/}{LinkedIn}
\end{center}
\vspace{15pt}

<!-- SUMMARY -->
\begin{large}{\bf SUMMARY}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.12cm}
Data Scientist with scientific research background, strong communication skills, and years of industry experience in a client-facing role. Demonstrated experience in scoping, developing, and delivering data/analytics projects, with an emphasis on predictive modeling, causal inference, and data visualization. Accomplished public speaker with featured talks and presentations at conferences and meetups throughout the state of Wisconsin.

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Languages and Tools}\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
*Proficient*: R, Python, Git/GitHub, SQL, Quarto, Shiny, Markdown, Tableau, Alteryx \newline
*Intermediate*: Docker, GCP/AWS/Azure \newline
Machine Learning, Causal Inference, Statistical Learning, Time Series, Research Design, Survey Design

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Florida State University}\end{flushleft}
    \begin{flushright}Tallahassee, FL\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Doctor of Philosophy: Political Science \end{flushleft}
  \end{multicols}
    \vspace{-0.17cm}
    \vspace{-0.17cm}
  \begin{flushleft}Dissertation: \textit{Applied Predictive Modeling for Measurement and Inference \newline in International Conflict and Political Violence}\end{flushleft}
\end{large}

\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Texas A\&M University}\end{flushleft}
    \begin{flushright}College Station, TX\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelor of Science: Political Science\end{flushleft}
  \end{multicols}
\end{large}
\vspace{1.5pt}

<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf AE Business Solutions}\end{flushleft}
    \begin{flushright}2022-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Senior Data Scientist}\end{flushleft}
    \begin{flushright}Madison, WI\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Work in a client-facing, project delivery role for data science/engineering/analytics use cases at enterprise organizations
* Act as technical liaison between data science teams and senior leadership, translating complex analyses into actionable recommendations and strategic decisions
* Train data scientists to implement DevOps processes tailored for data science and machine learning workflows

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf AE Business Solutions}\end{flushleft}
    \begin{flushright}2020-2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Data Scientist}\end{flushleft}
    \begin{flushright}Madison, WI\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Building data pipelines, training and assessing predictive models within client environments
* Assessing organizational practices for data science use cases and auditing models for performance, fairness, and bias
* Delivering hands-on training and "office hours" advising for clients on specialized topics within the fields of data science

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf AE Business Solutions}\end{flushleft}
    \begin{flushright}2018-2020\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Business Intelligence Engineer}\end{flushleft}
    \begin{flushright}Madison, WI\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Developing interactive dashboards and data visualizations to communicate insights and statistical methods to general public
* Training business and data analysts in research methods, data preparation, and data visualization (R, Alteryx, Tableau)

\vspace{7pt}

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Florida State University}\end{flushleft}
    \begin{flushright}2013-2018\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Research Assistant}\end
    {flushleft}\begin{flushright}Tallahassee, FL\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Performed statistical modeling in R and Stata for prediction and hypothesis testing in social science research.
* Assisted professors by collecting, cleaning, and preparing data sets for data visualization and presentation in academic research papers.
* Literature reviews of sub fields in international relations, comparative politics, statistics, and computer science.

\vspace{7pt}

\begin{large}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Instructor}\end
    {flushleft}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Created original syllabi and lecture materials for Political Violence, Civil Wars, and International Relations classes.
* Assigned research papers, working with students to develop their academic writing skills and mentor their applications for graduate school.
* Taught programming with R to graduate students and held supplementary sessions for statistical modeling and programming.

\vspace{7pt}

<!-- <!-- RESEARCH -->
<!-- \begin{large} -->
<!-- {\bf RESEARCH} -->
<!--   \vspace{3pt} -->
<!--   \hrule -->
<!-- \end{large} -->
<!-- \vspace{-0.16cm} -->
<!-- Predicting the Costs of War. \textit{Journal of Defense Modeling and Simulation}. Special Issue on Forecasting in the Social Sciences for National Security (J17-1). January 2020. -->

<!-- \vspace{7pt} -->

<!-- PERSONAL PROJECTS : 1ST BULLET -->
\begin{large}
{\bf PERSONAL PROJECTS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
Most of my work with clients is under NDA, making it difficult to provide detailed examples of my work. I do, however, frequently work on side projects in my free time to explore new methods and techniques that I can use in my consultant work. Here are some examples: 
  
\begin{large}
  \vspace{3pt}
  \begin{multicols}{2}
    \begin{flushleft}\textit{\href{https://phenrickson.github.io/boardgames.html}{Predicting Upcoming Board Games}}\end{flushleft}
    \begin{flushright}2022-2023\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* Created package for collecting BoardGameGeek (BGG) data to [train predictive models at the BGG community level (complexity, average rating, etc) for upcoming board game releases](https://phenrickson.github.io/bgg_models/)
* [Trained predictive models for individual users](https://phenrickson.github.io/bgg_collections/) to recommend new games to individuals [based on their collections](https://phenrickson.github.io/bgg_collections/).
* Developed pipelines to collect data on upcoming releases and deliver predictions from a suite of models (penalized linear regressions, xgboost, lightgbm) via GitHub Actions, Google Cloud Storage, and Quarto

\vspace{7pt}

<!-- PERSONAL PROJECTS : 2nd BULLET -->
\begin{large}
  \vspace{3pt}
  \begin{multicols}{2}
    \begin{flushleft}\textit{\href{https://phenrickson.github.io/cfb.html}{College Football Predictions and Rankings}}\end{flushleft}
    \begin{flushright}2024\end{flushright}
  \end{multicols}
  \vspace{-0.12cm}
\end{large}
* Estimating [opponent-adjusted team offensive/defensive efficiency](https://phenrickson.github.io/cfb_models/estimating_efficiency.html) for all FBS teams at the weekly level using play by play data and [predicted points added per play](https://phenrickson.github.io/cfb_models/expected_points.html).
* Use team efficiency ratings as inputs into my (Bayesian) game prediction model to [estimate team ratings](https://phenrickson.github.io/cfb_models/season_report.html) and [simulate upcoming college football games](https://phenrickson.github.io/cfb_models/predicting_games.html).
